// Copyright (c) 2026 Rudy Hartwig.
// Licensed under the MIT License.

package lib

import (
	"fmt"
	"log"
	"os"
	"strings"
	"time"
)

// ScanAutoGenMarker is embedded in headers written by 'watchdoc scan --fix'
// and is used to detect temp headers during subsequent scans.
const ScanAutoGenMarker = "auto-generated by 'watchdoc scan --fix'"

type headerWriter func(config *Config, path string, commentSyntax string, header *strings.Builder)

func WriteHeader(config *Config, path string) {
	commentSyntax, ok := commentSyntaxFor(config, path)
	if !ok {
		return
	}

	// Get pre-existing file contents to ensure that they
	// can be appended back after the header
	existingContents, err := os.ReadFile(path)
	if err != nil {
		log.Printf("Failed to create header for file '%v'\n", path)
		log.Println("Unable to read existing file contents")
		return
	}

	if strings.HasPrefix(string(existingContents), "#!") {
		return
	}

	// Check using only stable fields (excludes author, which varies per contributor)
	check := buildCheckHeader(config, path, commentSyntax)
	if check != "" && strings.HasPrefix(string(existingContents), check) {
		return
	}

	header := strings.Builder{}
	if config.CopyrightOnly {
		writeCopyright(config, path, commentSyntax, &header)
	} else {
		// Author is written last so it falls outside the prefix check above
		for i, writeFn := range []headerWriter{writeCopyright, writeFileName, writeCreatedAt, writeAuthor} {
			writeFn(config, path, commentSyntax, &header)
			if i == 0 {
				// One extra line between the copyright block and everything else
				header.WriteString(commentSyntax + "\n")
			}
		}
	}

	// Append back on any pre-existing file contents and write with header
	header.WriteString("\n" + string(existingContents))
	if err = os.WriteFile(path, []byte(header.String()), 0o644); err != nil {
		log.Printf("Unable to write to file '%v'. Skipping it\n", path)
	}

	fmt.Println("Successfully created header")
}

// WriteScanHeader writes a best-effort header for use with 'watchdoc scan --fix'.
// It uses "unknown" for the created date and appends an auto-gen note to signal
// that the header needs to be reviewed and updated by a human.
func WriteScanHeader(config *Config, path string) {
	commentSyntax, ok := commentSyntaxFor(config, path)
	if !ok {
		return
	}

	existingContents, err := os.ReadFile(path)
	if err != nil {
		log.Printf("Failed to create header for file '%v'\n", path)
		return
	}

	if strings.HasPrefix(string(existingContents), "#!") {
		return
	}

	check := buildCheckHeader(config, path, commentSyntax)
	if check != "" && strings.HasPrefix(string(existingContents), check) {
		return
	}

	header := strings.Builder{}
	if config.CopyrightOnly {
		writeCopyright(config, path, commentSyntax, &header)
	} else {
		writeCopyright(config, path, commentSyntax, &header)
		header.WriteString(commentSyntax + "\n")
		writeFileName(config, path, commentSyntax, &header)
		if config.CreatedAt {
			header.WriteString(commentSyntax + "Created: unknown\n")
		}
		writeAuthor(config, path, commentSyntax, &header)
	}
	header.WriteString(commentSyntax + "NOTE: " + ScanAutoGenMarker + ". Please verify and update.\n")

	header.WriteString("\n" + string(existingContents))
	if err = os.WriteFile(path, []byte(header.String()), 0o644); err != nil {
		log.Printf("Unable to write to file '%v'. Skipping it\n", path)
	}
}

// HasHeader reports whether the file at path already contains a valid header
// based on the stable fields of config (copyright, fileName, createdAt).
// The author field is intentionally excluded so headers written by different
// contributors are still recognised as valid.
func HasHeader(config *Config, path string, contents []byte) bool {
	commentSyntax, ok := commentSyntaxFor(config, path)
	if !ok {
		return false
	}
	check := buildCheckHeader(config, path, commentSyntax)
	if check == "" {
		return false
	}
	return strings.HasPrefix(string(contents), check)
}

// buildCheckHeader constructs the portion of the header used for existence
// checks. It omits the author field so that files headered by other
// contributors are not incorrectly treated as missing a header.
func buildCheckHeader(config *Config, path string, commentSyntax string) string {
	check := strings.Builder{}
	if config.CopyrightOnly {
		writeCopyright(config, path, commentSyntax, &check)
	} else {
		for i, writeFn := range []headerWriter{writeCopyright, writeFileName} {
			writeFn(config, path, commentSyntax, &check)
			if i == 0 {
				check.WriteString(commentSyntax + "\n")
			}
		}
	}
	return check.String()
}

// commentSyntaxFor returns the comment syntax string for the file at path,
// with a trailing space appended. Returns false if the extension is not
// present in config.
func commentSyntaxFor(config *Config, path string) (string, bool) {
	parts := strings.Split(path, ".")
	ext := parts[len(parts)-1]
	extension, ok := config.Extensions[ext]
	if !ok {
		return "", false
	}
	syntax := extension.CommentSyntax
	if syntax != "" {
		syntax += " "
	}
	return syntax, true
}

func writeCopyright(config *Config, path string, commentSyntax string, header *strings.Builder) {
	if config.Copyright == "" {
		return
	}

	for line := range strings.SplitSeq(config.Copyright, "\n") {
		header.WriteString(commentSyntax + line + "\n")
	}
}

func writeAuthor(config *Config, path string, commentSyntax string, header *strings.Builder) {
	if config.Author == "" {
		return
	}

	header.WriteString(commentSyntax + "Author: " + config.Author + "\n")
}

func writeCreatedAt(config *Config, path string, commentSyntax string, header *strings.Builder) {
	if !config.CreatedAt {
		return
	}

	today := time.Now().Format(time.RFC3339)
	today = strings.Split(today, "T")[0]
	header.WriteString(commentSyntax + "Created: " + today + "\n")
}

func writeFileName(config *Config, path string, commentSyntax string, header *strings.Builder) {
	if !config.FileName {
		return
	}

	header.WriteString(commentSyntax + "File: " + path + "\n")
}
